//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.02 at 07:34:28 PM EDT 
//


package org.jcp.xmlns.javaee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         [
 *         The servlet-link element is used in the service-impl-bean element
 *         to specify that a Service Implementation Bean is defined as a
 *         JAX-RPC Service Endpoint.
 *         
 *         The value of the servlet-link element must be the servlet-name of
 *         a JAX-RPC Service Endpoint in the same WAR file.
 *         
 *         Used in: service-impl-bean
 *         
 *         Example:
 *         	  <servlet-link>StockQuoteService</servlet-link>
 *         
 *         
 *       
 * 
 * <p>Java class for servlet-linkType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="servlet-linkType">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;http://xmlns.jcp.org/xml/ns/javaee>string">
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "servlet-linkType")
public class ServletLinkType
    extends String
{


}
