//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.02 at 07:34:28 PM EDT 
//


package org.jcp.xmlns.javaee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         [
 *         This type contains the fully-qualified Java type of the
 *         environment entry value that is expected by the
 *         application's code.
 *         
 *         The following are the legal values of env-entry-type-valuesType:
 *         
 *         java.lang.Boolean
 *         java.lang.Byte
 *         java.lang.Character
 *         java.lang.String
 *         java.lang.Short
 *         java.lang.Integer
 *         java.lang.Long
 *         java.lang.Float
 *         java.lang.Double
 *         		  java.lang.Class
 *         		  any enumeration type (i.e. a subclass of java.lang.Enum)
 *         
 *         Examples:
 *         
 *         <env-entry-type>java.lang.Boolean</env-entry-type>
 *         <env-entry-type>java.lang.Class</env-entry-type>
 *         <env-entry-type>com.example.Color</env-entry-type>
 *         
 *         
 *       
 * 
 * <p>Java class for env-entry-type-valuesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="env-entry-type-valuesType">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;http://xmlns.jcp.org/xml/ns/javaee>fully-qualified-classType">
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "env-entry-type-valuesType")
public class EnvEntryTypeValuesType
    extends FullyQualifiedClassType
{


}
